project_id = "fejvckhuhflndcjuoppy"

[functions.calculate-distance]
verify_jwt = false

[functions.send-invite]
verify_jwt = false

[functions.manage-entradas]
verify_jwt = true

[functions.manage-saidas]
verify_jwt = true

[functions.manage-estoque]
verify_jwt = true

[functions.manage-usuarios]
verify_jwt = true

[functions.manage-inventario]
verify_jwt = true

[functions.manage-viagens]
verify_jwt = true

[functions.manage-configuracoes]
verify_jwt = true

[functions.manage-comprovantes]
verify_jwt = true

[functions.manage-notifications]
verify_jwt = true

[functions.gerar-fatura]
verify_jwt = true

[functions.fechar-fatura]
verify_jwt = true

[functions.gerar-royalty]
verify_jwt = true

[functions.fechar-royalty]
verify_jwt = true

[functions.auto-fechar-faturas]
verify_jwt = false

[functions.auto-fechar-royalties]
verify_jwt = false

[functions.storage-positions-audit]
verify_jwt = true